### ISSUE TITLE
Possible GHA wrong name

### ISSUE THREAD

**Issue by edgd1er** [dmvict/clean-workflow-runs#1]
Using the example given in the readme I got the error here undo.
```
- name: Delete workflow runs
  uses: dmvict/clean-action@v1.0.0
  with:
    token: ${{ secrets.PRIVATE_GITHUB_TOKEN }}
    repo: user/repo
    branch: master
    run_conclusions: |
      failure
      timed_out
    save_period: 30
    save_min_runs_number: 1
    dry: true
```
```
Error: Unable to resolve action `dmvict/clean-action@v1.0.0`, repository not found
```

Replacing `clean-action` with `clean-workflow-run` did allow the action to run.
Is it the proper name to use ?

the minimum job would be:
```
- name: Delete workflow runs
        uses: dmvict/clean-workflow-runs@v1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
```
